# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aaammari <aaammari@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/26 10:29:57 by aaammari          #+#    #+#              #
#    Updated: 2023/08/27 11:57:37 by aaammari         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM debian:bullseye

RUN apt-get update && apt-get upgrade -y && apt-get install -y mariadb-server 

COPY ./tool/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY ./tool/mariadb.sh /tmp/mariadb.sh

EXPOSE 3306

CMD ["/bin/sh", "/tmp/mariadb.sh"]